### ISSUE TITLE
Fix design and data of each course page

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki.github.io#1]

**Comment by varughese** [comment]
Does this issue mean fix up this file https://github.com/PittCSWiki/pittcswiki.github.io/blob/master/helpers/courses/generate_page_skeletons.js

**Comment by azharichenko** [comment]
It's basically fixing design and getting data more data into the course pages

**Comment by azharichenko** [comment]
Just the start of a new component for testimonials dbe5045 . Though the data column names need to be modified cause lol really `termSzn`

**Comment by varughese** [comment]
Thanks - and that component/idea is still in an experimental phase
