### ISSUE TITLE
Add way for scheduling mock internships

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki.github.io#21]

**Comment by varughese** [comment]
i love this idea

**Comment by varughese** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSda2TehZsQkQH2cRrFOsES2iynowJION142K1Y-Di2eFWJuvw/viewform 

this is best we can do i think, just link this for now, see if gets traction

and lol "mock internships"
