### ISSUE TITLE
Develop systematic way to notify us if a new course is added

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki.github.io#26]
Right now the scraper scrapes courses.sci.pitt.edu and puts it in a file. We don't really need to run the scraper to update the courses, because we already have most of them.

But, we should still check the courses SCI offers, compare it to the ones we have, and notify of the newness so its easy for someone to check. 

So, fixing this entire mess:
https://github.com/PittCSWiki/pittcswiki.github.io/tree/master/helpers/courses

Similar to #1

**Comment by varughese** [comment]
Made it so that you can run

```
npm run check_correct_courses
```

and it will run a test to make sure the stuff on our end is up to date. I was thinkin we could run that on CI, but idk if we can make outbound network requests on free CI tools like travis. Plus, we only really need to run it 3 times a year (when summerr, fall, spring get updated). Close the issue if you think that is chillen @azharichenko , eventually ill start making pull requests and requesting reviews like a real developer

**Comment by azharichenko** [comment]
it's chilling, plus we know about when based on a Pitt calendar when to update. but it shouldn't matter too much except for maybe the edge case of CS 1699 and another equivalent course
