### ISSUE TITLE
Fix footer to have more information and better CSS styling and placement

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki.github.io#33]
it should say built with <3 by pittcs because we built it with love, link to the github source, loook a little nicer, and rn it is position fixed at the bottom instead being a good footer

**Comment by azharichenko** [comment]
Just added the heart icon to the bottom, also added font awesome to the project

**Comment by varughese** [comment]
https://medium.com/@fabianterh/fixing-flashing-huge-font-awesome-icons-on-a-gatsby-static-site-787e1cfb3a18 footer looks better now / in correct spot, but experiencing this bug
