### ISSUE TITLE
Add language guides

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki.github.io#48]
Give all the resources to give intuitive approach to learning the inner workings of different programming languages. And not just wow look you can do if statements and for loops but more focused on the design of the code, how the programming paradigms work.

**Comment by azharichenko** [comment]
So like the ultimate go language tutorial

**Comment by varughese** [comment]
links to resources right?
sort of related to - https://github.com/PittCSWiki/pittcswiki.github.io/issues/40

**Comment by azharichenko** [comment]
Didn't realize you thought of that already.
