### ISSUE TITLE
Add "credits" to course listing page

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki.github.io#54]
Forgot to add a label for credits in the course template page and course listing view. pretty sure the data is already there

**Comment by varughese** [comment]
Assinging this to use because its easy and will get you used to setting this repository and your dev environment up @Zmwang622 

Code Pointer - 

https://github.com/PittCSWiki/pittcswiki.github.io/blob/master/src/components/templates/courses-template.js#L61

**Comment by Zmwang622** [comment]
When do you want me to do this

**Comment by varughese** [comment]
May 15th

**Comment by Zmwang622** [comment]
@varughese Can we close this issue? Or do you want it to look better

**Comment by varughese** [comment]
Close it, you can do the honors. Also pro tip in your PR description if you
write closes #issuenum it will auto close

**Comment by Zmwang622** [comment]
oh hoipeeee
