### ISSUE TITLE
Guide about guide writing (metadata to guides)

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki.github.io#58]
Hmmmm so it would probably be a good idea to maintain some metadata about who wrote the guides and maybe how to contact them, or information about the title, etc. that could be beneficial to gatsby

**Comment by azharichenko** [comment]
I somewhat enjoy how jekyll does it with blog posts, for example...

```
---
layout: post
title:  "Welcome to Jekyll!"
---
```

**Comment by varughese** [comment]
yee, gatsby does the same thing, because they ripped off jekyll. all guides should be markdown files with that in the top (gatsby calls that portion the frontmatter)

**Comment by azharichenko** [comment]
sweet, well I think we should just have like a markdown file explaining this spec for peeps to easily make guides

**Comment by varughese** [comment]
100% , that is a little part of #25  . I made a `docs` folder.

but, meta, we could also put that spec on the wiki itself if wanted lol

**Comment by azharichenko** [comment]
Hmmm good idea would be to have one property indicating publishing state of the guide so until it has state `complete` then don't publish

**Comment by varughese** [comment]
ya like an in draft - but if someone makes a PR, and that is merged, shouldnt that be considered `complete`?

**Comment by varughese** [comment]
maybe we should think of some guiding principles (pun intended) for how to write these guides first, and put that in a doc.

I am thinking

- Brief
- Easy to read
- Unbiased
- High Quality
