### ISSUE TITLE
Adding an author tag to the guides

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki.github.io#83]
I think it would be nice right below the title of an article to give a space to who wrote it and optionally their email so people will additionaly questions and freely email the guides author

**Comment by varughese** [comment]
https://github.com/PittCSWiki/pittcswiki.github.io/blob/master/src/components/templates/guide-template.js#L28

it is adding this code:
```
            {frontmatter.author && (
              <h2 className="sub-title">{frontmatter.author}</h2>
            )}
```

**Comment by varughese** [comment]
and then add 'author' to the front matter of anything you want

**Comment by azharichenko** [comment]
🙌🙌🙌
